// Script to add sample products to Firestore
// Run this from admin panel or Node.js environment

export const sampleProducts = [
  // HEALTH CATEGORY
  {
    name: "Organic Multivitamin Complex",
    slug: "organic-multivitamin-complex",
    description:
      "Premium multivitamin supplement packed with essential vitamins and minerals. Made from organic whole foods for maximum absorption and bioavailability. Perfect for daily wellness support and immune system boost.",
    shortDescription:
      "Premium organic multivitamin for daily wellness and immune support",
    category: "health",
    subcategory: "Vitamins",
    brand: "WellnessPlus",
    price: 1499,
    originalPrice: 1999,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1550572017-4137bc593c6d?w=800",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1550572017-4137bc593c6d?w=800",
    stock: 150,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.5,
    reviews: 234,
    features: [
      "100% organic whole food ingredients",
      "No synthetic fillers or additives",
      "Vegan and gluten-free",
      "30-day supply (60 capsules)",
      "Third-party tested for purity",
    ],
    tags: ["vitamins", "organic", "immune support", "wellness"],
    specifications: {
      weight: "120g",
      dimensions: "6cm x 6cm x 12cm",
      ingredients:
        "Organic fruit & vegetable blend, vitamins A, C, D, E, K, B-complex",
      usage: "Take 2 capsules daily with food",
    },
  },
  {
    name: "Omega-3 Fish Oil Premium",
    slug: "omega-3-fish-oil-premium",
    description:
      "Ultra-pure Omega-3 fish oil supplement rich in EPA and DHA. Supports heart health, brain function, and joint mobility. Molecularly distilled for purity and potency.",
    shortDescription: "Premium Omega-3 for heart and brain health",
    category: "health",
    subcategory: "Supplements",
    brand: "HealthCore",
    price: 1299,
    originalPrice: 1799,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "amazon",
    affiliateUrl: "https://amazon.in",
    images: [
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800",
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    reviews: 456,
    features: [
      "1000mg EPA + DHA per serving",
      "Molecularly distilled for purity",
      "No fishy aftertaste",
      "60 softgel capsules",
      "Sustainably sourced",
    ],
    tags: ["omega-3", "fish oil", "heart health", "brain health"],
    specifications: {
      weight: "150g",
      dimensions: "7cm x 7cm x 13cm",
      ingredients: "Fish oil (anchovy, sardine), EPA, DHA, vitamin E",
      usage: "Take 2 softgels daily with meals",
    },
  },
  {
    name: "Probiotics Digestive Support",
    slug: "probiotics-digestive-support",
    description:
      "Advanced probiotic formula with 50 billion CFU and 12 probiotic strains. Supports digestive health, gut microbiome balance, and immune function.",
    shortDescription: "50 billion CFU probiotic for digestive wellness",
    category: "health",
    subcategory: "Digestive Health",
    brand: "GutHealth Pro",
    price: 1699,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800",
    stock: 89,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviews: 189,
    features: [
      "50 billion CFU per capsule",
      "12 diverse probiotic strains",
      "Delayed-release capsules",
      "Shelf-stable formula",
      "30-day supply",
    ],
    tags: ["probiotics", "gut health", "digestive", "immunity"],
    specifications: {
      weight: "90g",
      dimensions: "5cm x 5cm x 11cm",
      ingredients: "Lactobacillus, Bifidobacterium blend, prebiotics",
      usage: "Take 1 capsule daily on empty stomach",
    },
  },

  // SKINCARE CATEGORY
  {
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    description:
      "Powerful vitamin C serum that brightens skin tone, reduces dark spots, and boosts collagen production. Formulated with 20% pure L-ascorbic acid and hyaluronic acid for maximum efficacy.",
    shortDescription: "20% Vitamin C serum for radiant, youthful skin",
    category: "skincare",
    subcategory: "Serums",
    brand: "GlowLab",
    price: 2499,
    originalPrice: 3499,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    stock: 200,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    rating: 4.8,
    reviews: 567,
    features: [
      "20% pure L-ascorbic acid",
      "Reduces dark spots and hyperpigmentation",
      "Boosts collagen production",
      "Lightweight, fast-absorbing",
      "30ml bottle - 2 month supply",
    ],
    tags: ["vitamin c", "serum", "brightening", "anti-aging"],
    specifications: {
      weight: "50g",
      dimensions: "3cm x 3cm x 10cm",
      ingredients:
        "L-Ascorbic Acid 20%, Hyaluronic Acid, Vitamin E, Ferulic Acid",
      usage: "Apply 3-4 drops to clean face morning and evening",
    },
  },
  {
    name: "Hydrating Face Moisturizer",
    slug: "hydrating-face-moisturizer",
    description:
      "Ultra-hydrating daily moisturizer enriched with hyaluronic acid and ceramides. Locks in moisture for 24 hours while strengthening the skin barrier. Suitable for all skin types.",
    shortDescription: "24-hour hydration with hyaluronic acid",
    category: "skincare",
    subcategory: "Moisturizers",
    brand: "HydraGlow",
    price: 1799,
    currency: "INR",
    saleType: "direct",
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800"],
    thumbnail:
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    stock: 145,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.6,
    reviews: 342,
    features: [
      "24-hour hydration",
      "Hyaluronic acid + ceramides",
      "Non-comedogenic formula",
      "Fragrance-free",
      "50ml jar",
    ],
    tags: ["moisturizer", "hydrating", "hyaluronic acid", "skincare"],
    specifications: {
      weight: "80g",
      dimensions: "6cm x 6cm x 5cm",
      ingredients: "Hyaluronic Acid, Ceramides, Glycerin, Niacinamide",
      usage: "Apply to clean face twice daily",
    },
  },
  {
    name: "Gentle Cleansing Face Wash",
    slug: "gentle-cleansing-face-wash",
    description:
      "pH-balanced gentle face wash that effectively removes dirt, oil, and makeup without stripping skin. Enriched with aloe vera and chamomile for soothing cleansing.",
    shortDescription: "Gentle pH-balanced cleanser for all skin types",
    category: "skincare",
    subcategory: "Cleansers",
    brand: "PureClean",
    price: 899,
    originalPrice: 1199,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
    stock: 220,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    reviews: 289,
    features: [
      "pH-balanced formula",
      "Soap-free and sulfate-free",
      "Aloe vera + chamomile",
      "Suitable for sensitive skin",
      "150ml bottle",
    ],
    tags: ["cleanser", "face wash", "gentle", "sensitive skin"],
    specifications: {
      weight: "180g",
      dimensions: "5cm x 5cm x 15cm",
      ingredients: "Aloe Vera, Chamomile, Glycerin, Coconut-based surfactants",
      usage: "Apply to damp face, massage, rinse thoroughly",
    },
  },

  // HAIRCARE CATEGORY
  {
    name: "Argan Oil Hair Serum",
    slug: "argan-oil-hair-serum",
    description:
      "Luxurious argan oil hair serum that nourishes, repairs, and adds brilliant shine to damaged hair. Rich in vitamins and antioxidants for healthy, manageable hair.",
    shortDescription: "Nourishing argan oil for silky, shiny hair",
    category: "haircare",
    subcategory: "Hair Oil",
    brand: "SilkHair",
    price: 1299,
    originalPrice: 1799,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "flipkart",
    affiliateUrl: "https://flipkart.com",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800",
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    reviews: 423,
    features: [
      "100% pure Moroccan argan oil",
      "Repairs split ends",
      "Adds natural shine",
      "Heat protection",
      "60ml bottle",
    ],
    tags: ["argan oil", "hair serum", "shine", "repair"],
    specifications: {
      weight: "90g",
      dimensions: "4cm x 4cm x 12cm",
      ingredients: "Pure Argan Oil, Vitamin E, Essential fatty acids",
      usage: "Apply 2-3 drops to damp or dry hair ends",
    },
  },
  {
    name: "Biotin Hair Growth Shampoo",
    slug: "biotin-hair-growth-shampoo",
    description:
      "Strengthening shampoo infused with biotin and keratin to promote hair growth and reduce hair fall. Gentle formula suitable for daily use.",
    shortDescription: "Biotin-enriched shampoo for stronger, healthier hair",
    category: "haircare",
    subcategory: "Shampoo",
    brand: "GrowthPro",
    price: 799,
    currency: "INR",
    saleType: "direct",
    images: ["https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800"],
    thumbnail:
      "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800",
    stock: 167,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.3,
    reviews: 298,
    features: [
      "Biotin + keratin formula",
      "Promotes hair growth",
      "Reduces hair fall",
      "Sulfate-free",
      "300ml bottle",
    ],
    tags: ["biotin", "shampoo", "hair growth", "anti-hair fall"],
    specifications: {
      weight: "330g",
      dimensions: "6cm x 6cm x 18cm",
      ingredients: "Biotin, Keratin, Saw Palmetto, Caffeine",
      usage: "Massage into wet hair, lather, rinse thoroughly",
    },
  },
  {
    name: "Deep Conditioning Hair Mask",
    slug: "deep-conditioning-hair-mask",
    description:
      "Intensive repair hair mask with shea butter and coconut oil. Deeply conditions and restores moisture to dry, damaged hair. Weekly treatment for salon-soft results.",
    shortDescription: "Weekly intensive treatment for damaged hair",
    category: "haircare",
    subcategory: "Hair Mask",
    brand: "RepairX",
    price: 1099,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    stock: 98,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviews: 178,
    features: [
      "Shea butter + coconut oil",
      "Deep conditioning treatment",
      "Repairs damaged hair",
      "Adds moisture and softness",
      "200ml jar",
    ],
    tags: ["hair mask", "deep conditioning", "repair", "moisture"],
    specifications: {
      weight: "230g",
      dimensions: "7cm x 7cm x 6cm",
      ingredients: "Shea Butter, Coconut Oil, Argan Oil, Keratin",
      usage: "Apply to clean hair, leave for 15-20 mins, rinse",
    },
  },

  // PET CARE CATEGORY
  {
    name: "Premium Dog Shampoo - Oatmeal & Aloe",
    slug: "premium-dog-shampoo-oatmeal-aloe",
    description:
      "Gentle, hypoallergenic dog shampoo with oatmeal and aloe vera. Perfect for sensitive skin, soothes itching and leaves coat soft and shiny. Tearless formula.",
    shortDescription: "Gentle oatmeal shampoo for sensitive dog skin",
    category: "pets",
    subcategory: "Dogs",
    brand: "PawCare",
    price: 699,
    originalPrice: 999,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800",
    stock: 156,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    rating: 4.6,
    reviews: 512,
    features: [
      "Oatmeal + aloe vera formula",
      "Hypoallergenic & tearless",
      "Soothes itchy skin",
      "Pleasant vanilla scent",
      "500ml bottle",
    ],
    tags: ["dog shampoo", "oatmeal", "sensitive skin", "pet care"],
    specifications: {
      weight: "550g",
      dimensions: "7cm x 7cm x 20cm",
      ingredients: "Oatmeal Extract, Aloe Vera, Coconut Oil, Vitamin E",
      usage: "Wet coat, apply shampoo, massage, rinse thoroughly",
    },
  },
  {
    name: "Cat Dental Care Treats",
    slug: "cat-dental-care-treats",
    description:
      "Crunchy dental treats for cats that help reduce tartar and freshen breath. Veterinarian recommended for daily oral health maintenance.",
    shortDescription: "Tasty treats for healthy teeth and fresh breath",
    category: "pets",
    subcategory: "Cats",
    brand: "FelineFresh",
    price: 449,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "amazon",
    affiliateUrl: "https://amazon.in",
    images: ["https://images.unsplash.com/photo-1548681528-6a5c45b66b42?w=800"],
    thumbnail:
      "https://images.unsplash.com/photo-1548681528-6a5c45b66b42?w=800",
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.4,
    reviews: 234,
    features: [
      "Reduces tartar buildup",
      "Freshens breath",
      "Crunchy texture",
      "Chicken flavor",
      "200g pack",
    ],
    tags: ["cat treats", "dental care", "oral health", "pet snacks"],
    specifications: {
      weight: "200g",
      dimensions: "15cm x 10cm x 5cm",
      ingredients: "Chicken meal, Rice, Parsley, Mint",
      usage: "Give 5-10 treats daily as reward",
    },
  },
  {
    name: "Interactive Pet Feather Toy",
    slug: "interactive-pet-feather-toy",
    description:
      "Engaging interactive toy with feathers that keeps cats entertained for hours. Promotes exercise and mental stimulation. Durable construction with replaceable feathers.",
    shortDescription: "Fun interactive toy for active cats",
    category: "pets",
    subcategory: "Toys",
    brand: "PlayPaws",
    price: 349,
    currency: "INR",
    saleType: "direct",
    images: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800"],
    thumbnail:
      "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800",
    stock: 203,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.7,
    reviews: 456,
    features: [
      "Interactive design",
      "Colorful feathers",
      "Durable construction",
      "Replaceable parts",
      "Safe materials",
    ],
    tags: ["cat toy", "interactive", "feather", "play"],
    specifications: {
      weight: "50g",
      dimensions: "40cm length",
      ingredients: "N/A",
      usage: "Supervise play, replace worn feathers",
    },
  },

  // PARENTING CATEGORY
  {
    name: "Organic Baby Lotion - Lavender",
    slug: "organic-baby-lotion-lavender",
    description:
      "Gentle, organic baby lotion with calming lavender. Moisturizes delicate baby skin without harsh chemicals. Dermatologist tested and hypoallergenic.",
    shortDescription: "Gentle organic moisturizer for baby's delicate skin",
    category: "parenting",
    subcategory: "Baby Care",
    brand: "BabyPure",
    price: 599,
    originalPrice: 799,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800",
    stock: 189,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.8,
    reviews: 678,
    features: [
      "100% organic ingredients",
      "Calming lavender scent",
      "No parabens or sulfates",
      "Dermatologist tested",
      "200ml bottle",
    ],
    tags: ["baby lotion", "organic", "gentle", "moisturizer"],
    specifications: {
      weight: "230g",
      dimensions: "5cm x 5cm x 15cm",
      ingredients: "Organic Aloe, Lavender Oil, Shea Butter, Chamomile",
      usage: "Apply to clean skin after bath",
    },
  },
  {
    name: "Silicone Baby Feeding Set",
    slug: "silicone-baby-feeding-set",
    description:
      "Complete feeding set with BPA-free silicone plates, bowls, and utensils. Microwave and dishwasher safe. Perfect for toddlers learning to eat independently.",
    shortDescription: "Complete BPA-free silicone feeding set",
    category: "parenting",
    subcategory: "Feeding",
    brand: "TinyEats",
    price: 1299,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "flipkart",
    affiliateUrl: "https://flipkart.com",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviews: 345,
    features: [
      "BPA-free silicone",
      "5-piece set",
      "Microwave safe",
      "Dishwasher safe",
      "Multiple colors",
    ],
    tags: ["baby feeding", "silicone", "BPA-free", "dinnerware"],
    specifications: {
      weight: "400g",
      dimensions: "25cm x 20cm x 8cm",
      ingredients: "N/A",
      usage: "Wash before first use, microwave/dishwasher safe",
    },
  },
  {
    name: "Educational Learning Toys Set",
    slug: "educational-learning-toys-set",
    description:
      "Montessori-inspired educational toy set that promotes cognitive development, motor skills, and creativity. Safe, non-toxic materials for ages 1-3 years.",
    shortDescription: "Montessori toys for early learning and development",
    category: "parenting",
    subcategory: "Toys",
    brand: "LearnPlay",
    price: 2199,
    originalPrice: 2999,
    currency: "INR",
    saleType: "direct",
    images: ["https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800"],
    thumbnail:
      "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800",
    stock: 78,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    rating: 4.9,
    reviews: 892,
    features: [
      "Montessori-inspired design",
      "Promotes cognitive development",
      "Non-toxic materials",
      "Ages 1-3 years",
      "10-piece set",
    ],
    tags: ["educational toys", "montessori", "learning", "toddler"],
    specifications: {
      weight: "1.2kg",
      dimensions: "30cm x 25cm x 15cm",
      ingredients: "N/A",
      usage: "Adult supervision recommended for young children",
    },
  },
];
