// Second set of 15 sample products - completely different from the first set

export const sampleProducts2 = [
  // HEALTH CATEGORY
  {
    name: "Premium Collagen Peptides Powder",
    slug: "premium-collagen-peptides-powder",
    description:
      "Hydrolyzed collagen peptides from grass-fed bovine sources. Supports skin elasticity, joint health, and hair growth. Unflavored and easily dissolves in hot or cold beverages. Clinically proven to reduce wrinkles and improve skin hydration.",
    shortDescription: "Grass-fed collagen for skin, joints, and hair health",
    category: "health",
    subcategory: "Supplements",
    brand: "VitalCollagen",
    price: 2299,
    originalPrice: 2999,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800",
    stock: 120,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviews: 189,
    features: [
      "Grass-fed bovine collagen",
      "Type I & III collagen peptides",
      "20g protein per serving",
      "Unflavored and odorless",
      "450g (30 servings)",
    ],
    tags: ["collagen", "skin care", "joint health", "protein"],
    specifications: {
      weight: "450g",
      dimensions: "10cm x 10cm x 15cm",
      ingredients: "Hydrolyzed bovine collagen peptides",
      usage: "Mix 1 scoop (15g) with water, coffee, or smoothie daily",
    },
  },
  {
    name: "Ashwagandha Root Extract Capsules",
    slug: "ashwagandha-root-extract-capsules",
    description:
      "Organic Ashwagandha root extract standardized to 5% withanolides. Ancient Ayurvedic adaptogen known for stress relief, anxiety reduction, and improved sleep quality. Supports healthy cortisol levels and energy balance.",
    shortDescription: "Organic adaptogen for stress relief and better sleep",
    category: "health",
    subcategory: "Herbal Supplements",
    brand: "HerbalVeda",
    price: 899,
    originalPrice: 1299,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "amazon",
    affiliateUrl: "https://amzn.to/ashwagandha-extract",
    images: [
      "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800",
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviews: 312,
    features: [
      "500mg per capsule",
      "5% withanolides standardization",
      "Organic certified",
      "60 vegan capsules",
      "Third-party tested",
    ],
    tags: ["ashwagandha", "stress relief", "adaptogen", "sleep"],
    specifications: {
      weight: "85g",
      dimensions: "5cm x 5cm x 10cm",
      ingredients: "Organic Ashwagandha root extract (Withania somnifera)",
      usage: "Take 1-2 capsules daily with meals",
    },
  },
  {
    name: "Apple Cider Vinegar Gummies",
    slug: "apple-cider-vinegar-gummies",
    description:
      "Delicious apple-flavored gummies with the benefits of apple cider vinegar without the harsh taste. Supports digestion, metabolism, and weight management. Enhanced with Vitamin B12 and folic acid for energy support.",
    shortDescription: "Tasty ACV gummies for digestion and metabolism",
    category: "health",
    subcategory: "Digestive Health",
    brand: "NutriGummy",
    price: 699,
    originalPrice: 999,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=800",
      "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=800",
    stock: 200,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    reviews: 156,
    features: [
      "500mg ACV per gummy",
      "Added Vitamin B12 & folic acid",
      "Pectin-based (vegan)",
      "60 gummies per bottle",
      "Natural apple flavor",
    ],
    tags: ["acv", "gummies", "digestion", "metabolism"],
    specifications: {
      weight: "180g",
      dimensions: "7cm x 7cm x 11cm",
      ingredients: "Apple cider vinegar powder, pectin, B12, folic acid",
      usage: "Chew 2 gummies daily before meals",
    },
  },

  // SKINCARE CATEGORY
  {
    name: "Retinol Night Cream 2.5%",
    slug: "retinol-night-cream-2-5",
    description:
      "High-potency retinol night cream that reduces fine lines, wrinkles, and age spots. Formulated with hyaluronic acid and vitamin E for deep hydration. Gentle enough for sensitive skin with time-release technology.",
    shortDescription: "Powerful anti-aging night cream with retinol",
    category: "skincare",
    subcategory: "Anti-Aging",
    brand: "YouthGlow",
    price: 1599,
    originalPrice: 2199,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    stock: 85,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    rating: 4.8,
    reviews: 278,
    features: [
      "2.5% pure retinol",
      "Time-release formula",
      "Hyaluronic acid & Vitamin E",
      "50ml premium jar",
      "Dermatologist tested",
    ],
    tags: ["retinol", "anti-aging", "night cream", "wrinkles"],
    specifications: {
      weight: "50ml",
      dimensions: "6cm x 6cm x 7cm",
      ingredients: "Retinol 2.5%, hyaluronic acid, vitamin E, shea butter",
      usage: "Apply pea-sized amount to clean face before bed",
    },
  },
  {
    name: "Niacinamide 10% + Zinc Serum",
    slug: "niacinamide-10-zinc-serum",
    description:
      "Brightening serum with 10% niacinamide and 1% zinc to minimize pores, control oil, and even skin tone. Reduces blemishes and improves skin texture. Lightweight, fast-absorbing formula suitable for all skin types.",
    shortDescription: "Pore-minimizing serum for clear, bright skin",
    category: "skincare",
    subcategory: "Serums",
    brand: "GlowLab",
    price: 799,
    originalPrice: 1099,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "flipkart",
    affiliateUrl: "https://fkrt.it/niacinamide-serum",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800",
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.6,
    reviews: 421,
    features: [
      "10% niacinamide concentration",
      "1% zinc PCA",
      "Oil-free formula",
      "30ml dropper bottle",
      "Vegan & cruelty-free",
    ],
    tags: ["niacinamide", "serum", "pores", "brightening"],
    specifications: {
      weight: "30ml",
      dimensions: "3cm x 3cm x 10cm",
      ingredients: "Niacinamide 10%, zinc PCA 1%, hyaluronic acid",
      usage: "Apply 3-4 drops to face twice daily after cleansing",
    },
  },
  {
    name: "Charcoal Clay Face Mask",
    slug: "charcoal-clay-face-mask",
    description:
      "Detoxifying face mask with activated charcoal and kaolin clay. Deep cleans pores, removes impurities, and controls excess oil. Enhanced with tea tree oil for antibacterial benefits. Perfect for oily and acne-prone skin.",
    shortDescription: "Deep-cleansing mask for clear, refreshed skin",
    category: "skincare",
    subcategory: "Masks",
    brand: "PureDetox",
    price: 649,
    originalPrice: 899,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1556228852-80a1e49cfc90?w=800",
      "https://images.unsplash.com/photo-1594998893017-36147cbfc098?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1556228852-80a1e49cfc90?w=800",
    stock: 145,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviews: 198,
    features: [
      "Activated bamboo charcoal",
      "Kaolin & bentonite clay",
      "Tea tree oil",
      "100g jar (20 applications)",
      "Paraben-free",
    ],
    tags: ["charcoal", "clay mask", "detox", "pores"],
    specifications: {
      weight: "100g",
      dimensions: "7cm x 7cm x 5cm",
      ingredients: "Activated charcoal, kaolin clay, tea tree oil, aloe vera",
      usage: "Apply thin layer, leave for 10-15 mins, rinse with warm water",
    },
  },

  // HAIRCARE CATEGORY
  {
    name: "Keratin Hair Treatment Mask",
    slug: "keratin-hair-treatment-mask",
    description:
      "Professional-grade keratin treatment mask that repairs damaged hair, reduces frizz, and restores shine. Infused with argan oil and silk proteins for silky smooth results. Salon-quality treatment at home.",
    shortDescription: "Salon-quality keratin mask for smooth, shiny hair",
    category: "haircare",
    subcategory: "Hair Masks",
    brand: "SilkPro",
    price: 1199,
    originalPrice: 1699,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1526045478516-99145907023c?w=800",
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1526045478516-99145907023c?w=800",
    stock: 95,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviews: 167,
    features: [
      "Hydrolyzed keratin protein",
      "Argan oil & silk proteins",
      "Reduces frizz up to 95%",
      "200ml professional jar",
      "Sulfate & paraben free",
    ],
    tags: ["keratin", "hair mask", "frizz control", "smoothing"],
    specifications: {
      weight: "200ml",
      dimensions: "8cm x 8cm x 6cm",
      ingredients: "Keratin, argan oil, silk proteins, shea butter",
      usage: "Apply to damp hair, leave 10-15 mins, rinse thoroughly",
    },
  },
  {
    name: "Rosemary Mint Hair Growth Oil",
    slug: "rosemary-mint-hair-growth-oil",
    description:
      "Natural hair growth oil blend with rosemary, peppermint, and castor oil. Stimulates scalp circulation, strengthens hair roots, and promotes new growth. Reduces hair fall and improves hair thickness naturally.",
    shortDescription: "Natural oil blend for hair growth and thickness",
    category: "haircare",
    subcategory: "Hair Oils",
    brand: "BotaniGrow",
    price: 549,
    originalPrice: 799,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "amazon",
    affiliateUrl: "https://amzn.to/rosemary-hair-oil",
    images: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800",
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.5,
    reviews: 234,
    features: [
      "Rosemary & peppermint essential oils",
      "Cold-pressed castor oil base",
      "Promotes hair growth",
      "100ml bottle with dropper",
      "100% natural ingredients",
    ],
    tags: ["hair oil", "rosemary", "hair growth", "natural"],
    specifications: {
      weight: "100ml",
      dimensions: "4cm x 4cm x 12cm",
      ingredients: "Castor oil, rosemary oil, peppermint oil, vitamin E",
      usage: "Massage into scalp, leave for 2+ hours or overnight, wash",
    },
  },
  {
    name: "Purple Shampoo for Blonde Hair",
    slug: "purple-shampoo-blonde-hair",
    description:
      "Professional purple toning shampoo that neutralizes brassy yellow tones in blonde, silver, and gray hair. Maintains cool, vibrant tones between salon visits. Enriched with keratin and UV protection.",
    shortDescription: "Toning shampoo for vibrant blonde hair",
    category: "haircare",
    subcategory: "Shampoos",
    brand: "BlondeBeauty",
    price: 899,
    originalPrice: 1299,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800",
    stock: 110,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    reviews: 189,
    features: [
      "Violet pigments for toning",
      "Keratin-enriched formula",
      "UV protection",
      "300ml professional bottle",
      "Sulfate-free",
    ],
    tags: ["purple shampoo", "blonde", "toning", "color-safe"],
    specifications: {
      weight: "300ml",
      dimensions: "6cm x 6cm x 18cm",
      ingredients: "Violet pigments, keratin, coconut oil, UV filters",
      usage: "Use 1-2 times weekly, lather, leave 3-5 mins, rinse",
    },
  },

  // PETS CATEGORY
  {
    name: "Dental Sticks for Dogs - Mint Flavor",
    slug: "dental-sticks-dogs-mint",
    description:
      "Veterinarian-recommended dental chews that clean teeth, freshen breath, and reduce plaque buildup. Made with natural ingredients and mint extract. Perfect daily treat for medium to large dogs. Grain-free formula.",
    shortDescription: "Dental chews for cleaner teeth and fresh breath",
    category: "pets",
    subcategory: "Dog Treats",
    brand: "PawFresh",
    price: 449,
    originalPrice: 599,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800",
      "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800",
    stock: 180,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviews: 312,
    features: [
      "Reduces plaque & tartar",
      "Natural mint extract",
      "Grain-free formula",
      "30 sticks per pack",
      "Vet recommended",
    ],
    tags: ["dog treats", "dental", "breath", "natural"],
    specifications: {
      weight: "450g",
      dimensions: "15cm x 10cm x 20cm",
      ingredients: "Potato starch, glycerin, mint extract, calcium",
      usage: "Give 1 stick daily for dogs 15kg+",
    },
  },
  {
    name: "Interactive Cat Laser Toy",
    slug: "interactive-cat-laser-toy",
    description:
      "Automatic laser toy that keeps cats entertained for hours. Features random patterns, adjustable height, and timer settings. Battery-operated with auto-shutoff. Perfect for indoor cats who need exercise and mental stimulation.",
    shortDescription: "Automatic laser toy for active cat playtime",
    category: "pets",
    subcategory: "Cat Toys",
    brand: "FeliFun",
    price: 1299,
    originalPrice: 1799,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "flipkart",
    affiliateUrl: "https://fkrt.it/cat-laser-toy",
    images: [
      "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800",
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800",
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.4,
    reviews: 156,
    features: [
      "Automatic random patterns",
      "Adjustable height (360° rotation)",
      "Timer: 15/30/45 min settings",
      "Battery operated (3x AA)",
      "Auto-shutoff feature",
    ],
    tags: ["cat toy", "laser", "interactive", "automatic"],
    specifications: {
      weight: "250g",
      dimensions: "12cm x 12cm x 8cm",
      ingredients: "N/A (Electronic toy)",
      usage: "Place on floor, set timer, let cat play",
    },
  },
  {
    name: "Omega-3 Fish Oil for Pets",
    slug: "omega-3-fish-oil-pets",
    description:
      "Premium fish oil supplement for dogs and cats. Supports healthy skin, shiny coat, joint health, and immune function. Wild-caught fish source with natural lemon flavor. Easy pump dispenser for precise dosing.",
    shortDescription: "Fish oil for healthy skin, coat, and joints",
    category: "pets",
    subcategory: "Pet Supplements",
    brand: "PetWellness",
    price: 799,
    originalPrice: 1099,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800",
      "https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800",
    stock: 135,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.8,
    reviews: 267,
    features: [
      "Wild-caught fish source",
      "EPA & DHA omega-3s",
      "Natural lemon flavor",
      "250ml pump bottle",
      "For dogs and cats",
    ],
    tags: ["fish oil", "omega-3", "supplements", "coat"],
    specifications: {
      weight: "250ml",
      dimensions: "6cm x 6cm x 15cm",
      ingredients: "Wild fish oil, vitamin E, natural lemon flavor",
      usage: "Add 1 pump per 10kg body weight to food daily",
    },
  },

  // PARENTING CATEGORY
  {
    name: "Organic Baby Food Maker",
    slug: "organic-baby-food-maker",
    description:
      "All-in-one baby food maker that steams, blends, and warms food. BPA-free construction with large capacity bowl. Makes fresh, nutritious baby food in minutes. Includes recipe book and storage containers.",
    shortDescription: "Steam & blend fresh baby food in minutes",
    category: "parenting",
    subcategory: "Baby Feeding",
    brand: "TinyChef",
    price: 3499,
    originalPrice: 4999,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
      "https://images.unsplash.com/photo-1603147492650-65f7a4e6b451?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
    stock: 45,
    inStock: true,
    isActive: true,
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviews: 145,
    features: [
      "Steam & blend function",
      "700ml capacity",
      "BPA-free materials",
      "Includes 4 storage cups",
      "Recipe book included",
    ],
    tags: ["baby food", "steamer", "blender", "organic"],
    specifications: {
      weight: "1.5kg",
      dimensions: "20cm x 18cm x 25cm",
      ingredients: "N/A (Kitchen appliance)",
      usage: "Add ingredients, steam, then blend to desired consistency",
    },
  },
  {
    name: "Silicone Baby Teething Toys Set",
    slug: "silicone-baby-teething-toys-set",
    description:
      "Food-grade silicone teething toys in fun shapes and colors. Textured surface soothes sore gums and promotes sensory development. Freezer-safe for extra relief. Easy to clean and dishwasher safe. Set of 5 toys.",
    shortDescription: "Safe, soothing teething toys for babies",
    category: "parenting",
    subcategory: "Baby Toys",
    brand: "GumBuddy",
    price: 599,
    originalPrice: 899,
    currency: "INR",
    saleType: "affiliate",
    affiliateProvider: "amazon",
    affiliateUrl: "https://amzn.to/baby-teething-toys",
    images: [
      "https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=800",
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=800",
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    rating: 4.7,
    reviews: 289,
    features: [
      "100% food-grade silicone",
      "BPA, PVC, phthalate-free",
      "Freezer & dishwasher safe",
      "Set of 5 different shapes",
      "Textured for gum massage",
    ],
    tags: ["teething", "baby toys", "silicone", "safe"],
    specifications: {
      weight: "150g",
      dimensions: "Various (8-10cm each)",
      ingredients: "100% food-grade silicone",
      usage: "Freeze for extra relief, clean before first use",
    },
  },
  {
    name: "Baby Milestone Cards Set",
    slug: "baby-milestone-cards-set",
    description:
      "Beautiful illustrated milestone cards to capture baby's first year. Includes 48 cards covering monthly milestones, first words, first steps, and special moments. Perfect for photos and memory keeping. Comes with keepsake box.",
    shortDescription: "Capture precious first-year moments with photo cards",
    category: "parenting",
    subcategory: "Baby Gifts",
    brand: "MemoryKeep",
    price: 799,
    originalPrice: 1199,
    currency: "INR",
    saleType: "direct",
    images: [
      "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800",
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800",
    stock: 165,
    inStock: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    rating: 4.8,
    reviews: 198,
    features: [
      "48 illustrated cards",
      "Premium cardstock quality",
      "Gender-neutral designs",
      "Keepsake box included",
      "Photo-ready size (15x10cm)",
    ],
    tags: ["milestone", "baby cards", "photos", "keepsake"],
    specifications: {
      weight: "300g",
      dimensions: "16cm x 11cm x 3cm (box)",
      ingredients: "N/A (Paper products)",
      usage: "Use for monthly photos and special milestone moments",
    },
  },
];
